# Generated by Django 3.2.10 on 2022-01-21 12:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletedexpense',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deletedexpense',
            name='date',
            field=models.DateField(default=datetime.date(2022, 1, 21)),
        ),
        migrations.AlterField(
            model_name='deletedexpense',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=datetime.date(2022, 1, 21)),
        ),
    ]
